In [38]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [39]:
data = pd.read_json('Dados\Telco-Customer-Churn.json')
data

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
7263,9992-RRAMN,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7264,9992-UJOEL,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7265,9993-LHIEB,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."
7266,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."

In [40]:
customer = pd.json_normalize(data.customer)
internet = pd.json_normalize(data.internet)
phone = pd.json_normalize(data.phone)
account = pd.json_normalize(data.account)

In [41]:
customer['Churn'] = data.Churn

In [42]:
data1 = pd.concat([customer, internet], axis=1)
data2 = pd.concat([phone, account], axis=1)
data_final = pd.concat([data1, data2], axis=1)

In [43]:
data_final.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,Churn,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PhoneService,MultipleLines,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,Female,0,Yes,Yes,9,No,DSL,No,Yes,No,Yes,Yes,No,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,Male,0,No,No,9,No,DSL,No,No,No,No,No,Yes,Yes,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,Male,0,No,No,4,Yes,Fiber optic,No,No,Yes,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,Male,1,Yes,No,13,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Yes,No,Month-to-month,Yes,Electronic check,98.0,1237.85
4,Female,1,Yes,No,3,Yes,Fiber optic,No,No,No,Yes,Yes,No,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [44]:
data_final.columns[:]

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'Churn',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'PhoneService',
       'MultipleLines', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'Charges.Monthly', 'Charges.Total'],
      dtype='object')

In [45]:
renomear_coluna ={
    'gender' : 'GÃªnero',
    'SeniorCitizen' : 'Idoso',
    'Partner' : 'Parceiro',
    'Dependents' : 'Dependentes',
    'tenure' : 'Fidelidade',
    'InternetService' : 'Internet',
    'OnlineSecurity' : 'SeguranÃ§a Online',
    'OnlineBackup' : 'Backup Online',
    'DeviceProtection' : 'ProteÃ§Ã£o no Dispositivo',
    'TechSupport' : 'Suporte TÃ©cnico',
    'StreamingTV' : 'TV a Cabo',
    'StreamingMovies' : 'Streaming de Filmes',
    'PhoneService' : 'ServiÃ§o TelefÃ´nico',
    'MultipleLines' : 'Diversas Linhas de Telefone',
    'Contract' : 'Contrato',
    'PaperlessBilling' : 'Fatura Online',
    'PaymentMethod' : 'MÃ©todo de Pagamento',
    'Charges.Monthly' : 'Despesa Mensal',
    'Charges.Total' : 'Despesa Total'
}

In [46]:
data_final.rename(columns = renomear_coluna, inplace = True)
data_final['TV a Cabo'].value_counts()

No                     2896
Yes                    2790
No internet service    1581
Name: TV a Cabo, dtype: int64

In [47]:
renomear_info ={
    'Yes' : 'Sim',
    'No' : 'NÃ£o',
    'Fiber optic' : 'Fibra Ã³tica',
    'One year' : 'Um ano',
    'Month-to-month' : 'Mensal',
    'Two year' : 'Dois anos',
    'Electronic check' : 'DÃ©bito eletrÃ´nico',
    'Mailed check' : 'Pagamento fÃ­sico',
    'No phone service' : 'Sem serviÃ§o telefÃ´nico',
    'No internet service' : 'Sem internet',
    'Bank transfer (automatic) ' : 'AutomÃ¡tico DÃ©bito',
    'Credit transfer (automatic) ' : 'AutomÃ¡tico CrÃ©dito',
    ' ' : np.nan,
    '' : np.nan
}

In [48]:
data_final.Churn.value_counts(normalize = True) * 100

No     71.198569
Yes    25.719004
        3.082427
Name: Churn, dtype: float64

In [49]:
#data_final = data_final[data_final['Churn'] != '']

In [50]:
data_final.replace(renomear_info, inplace = True)

In [51]:
empty_val = (data_final.isnull() | data_final.empty | data_final.isna()).sum()
empty_val

GÃªnero                           0
Idoso                            0
Parceiro                         0
Dependentes                      0
Fidelidade                       0
Churn                          224
Internet                         0
SeguranÃ§a Online                 0
Backup Online                    0
ProteÃ§Ã£o no Dispositivo          0
Suporte TÃ©cnico                  0
TV a Cabo                        0
Streaming de Filmes              0
ServiÃ§o TelefÃ´nico               0
Diversas Linhas de Telefone      0
Contrato                         0
Fatura Online                    0
MÃ©todo de Pagamento              0
Despesa Mensal                   0
Despesa Total                   11
dtype: int64

In [52]:
idx = data_final[data_final["Despesa Total"].isna()].index

In [53]:
data_final.loc[idx, "Despesa Total"] = data_final.loc[idx, "Despesa Mensal"]
data_final['Despesa Total'] = data_final['Despesa Total'].astype(float)

In [54]:
data_final.drop(index = data_final[data_final.Churn.isna()].index, inplace = True)
data_final.reset_index(inplace = True, drop = True)

In [55]:
data_final['Gasto DiÃ¡rio'] = round(data_final['Despesa Total'] / ((data_final['Fidelidade'] + 1) * 30), 2)

In [56]:
data_final[['Despesa Total', 'Gasto DiÃ¡rio', 'Fidelidade']]

      Despesa Total  Gasto DiÃ¡rio  Fidelidade
0            593.30          1.98           9
1            542.40          1.81           9
2            280.85          1.87           4
3           1237.85          2.95          13
4            267.40          2.23           3
...             ...           ...         ...
7038         742.90          1.77          13
7039        1873.70          2.72          22
7040          92.75          1.03           2
7041        4627.65          2.27          67
7042        3707.60          1.93          63

[7043 rows x 3 columns]

In [58]:
data_final

,GÃªnero,Idoso,Parceiro,Dependentes,Fidelidade,Churn,Internet,SeguranÃ§a Online,Backup Online,ProteÃ§Ã£o no Dispositivo,...,TV a Cabo,Streaming de Filmes,ServiÃ§o TelefÃ´nico,Diversas Linhas de Telefone,Contrato,Fatura Online,MÃ©todo de Pagamento,Despesa Mensal,Despesa Total,Gasto DiÃ¡rio
0,Female,0,Sim,Sim,9,NÃ£o,DSL,NÃ£o,Sim,NÃ£o,...,Sim,NÃ£o,Sim,NÃ£o,Um ano,Sim,Pagamento fÃ­sico,65.60,593.30,1.98
1,Male,0,NÃ£o,NÃ£o,9,NÃ£o,DSL,NÃ£o,NÃ£o,NÃ£o,...,NÃ£o,Sim,Sim,Sim,Mensal,NÃ£o,Pagamento fÃ­sico,59.90,542.40,1.81
2,Male,0,NÃ£o,NÃ£o,4,Sim,Fibra Ã³tica,NÃ£o,NÃ£o,Sim,...,NÃ£o,NÃ£o,Sim,NÃ£o,Mensal,Sim,DÃ©bito eletrÃ´nico,73.90,280.85,1.87
3,Male,1,Sim,NÃ£o,13,Sim,Fibra Ã³tica,NÃ£o,Sim,Sim,...,Sim,Sim,Sim,NÃ£o,Mensal,Sim,DÃ©bito eletrÃ´nico,98.00,1237.85,2.95
4,Female,1,Sim,NÃ£o,3,Sim,Fibra Ã³tica,NÃ£o,NÃ£o,NÃ£o,...,Sim,NÃ£o,Sim,NÃ£o,Mensal,Sim,Pagamento fÃ­sico,83.90,267.40,2.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Female,0,NÃ£o,NÃ£o,13,NÃ£o,DSL,Sim,NÃ£o,NÃ£o,...,NÃ£o,NÃ£o,Sim,NÃ£o,Um ano,NÃ£o,Pagamento fÃ­sico,55.15,742.90,1.77
7039,Male,0,Sim,NÃ£o,22,Sim,Fibra Ã³tica,NÃ£o,NÃ£o,NÃ£o,...,NÃ£o,Sim,Sim,Sim,Mensal,Sim,DÃ©bito eletrÃ´nico,85.10,1873.70,2.72
7040,Male,0,NÃ£o,NÃ£o,2,NÃ£o,DSL,NÃ£o,Sim,NÃ£o,...,NÃ£o,NÃ£o,Sim,NÃ£o,Mensal,Sim,Pagamento fÃ­sico,50.30,92.75,1.03
7041,Male,0,Sim,Sim,67,NÃ£o,DSL,Sim,NÃ£o,Sim,...,NÃ£o,Sim,Sim,NÃ£o,Dois anos,NÃ£o,Pagamento fÃ­sico,67.85,4627.65,2.27
7042,Male,0,Sim,Sim,63,NÃ£o,DSL,Sim,Sim,Sim,...,Sim,Sim,NÃ£o,Sem serviÃ§o telefÃ´nico,Dois anos,NÃ£o,DÃ©bito eletrÃ´nico,59.00,3707.60,1.93

In [59]:
data_final.to_json('Dados\BaseLimpa.json')